# Generated by Django 5.2.5 on 2025-08-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('page', models.TextField(default='1:1')),
                ('text', models.TextField(unique=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=1.0)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('text',), name='unique_quote')],
            },
        ),
    ]
