# Generated by Django 5.2.5 on 2025-08-27 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='page',
        ),
    ]
