# Generated by Django 5.2.5 on 2025-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0002_remove_quote_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quotes/'),
        ),
    ]
