# Generated by Django 5.2.5 on 2025-08-28 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0003_quote_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('is_like', models.BooleanField()),
                ('quote',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pp.quote')),
            ],
            options={
                'unique_together': {('quote', 'session_key')},
            },
        ),
    ]
