# Generated by Django 5.2.5 on 2025-08-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0004_remove_quote_dislikes_remove_quote_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
        migrations.AlterField(
            model_name='vote',
            name='session_key',
            field=models.CharField(max_length=255),
        ),
    ]
