# Generated by Django 5.2.5 on 2025-08-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0005_remove_quote_dislikes_remove_quote_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='image',
        ),
        migrations.AddField(
            model_name='quote',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
