# Generated by Django 5.2.5 on 2025-08-30 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pp', '0006_remove_quote_image_quote_dislikes_quote_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
